# ExecMCP 配置示例
# 包含基本的 SSH 主机配置、安全规则和脚本定义

server:
  bind_addr: "127.0.0.1:7458"         # SSE 监听地址
  public_base_url: "http://localhost:7458"  # 客户端访问服务器的基础 URL
  log_level: "info"                    # 日志级别: debug|info|warn|error
  max_concurrent: 32                   # 最大并发请求数
  request_timeout_sec: 30              # 默认请求超时时间
  auth_token: "your-secret-token"      # 认证令牌（可选）

# SSH 主机配置
ssh_hosts: []
ssh_hosts_includes:
  - "etc/ssh_hosts.yaml"

# 安全配置
security: []
security_includes:
  - "etc/security.yaml"

# 定制脚本配置
scripts: []
scripts_includes:
  - "etc/scripts.yaml"

# 日志配置
logging:
  level: "info"                       # 日志级别
  format: "json"                      # 日志格式: json|text
  output: "stdout"                    # 输出位置: stdout|file
  file_path: "/var/log/mcpserver.log" # 日志文件路径（如果 output=file）
  max_size: "100MB"                   # 单个日志文件最大大小
  max_backups: 5                      # 保留的日志文件数量
  max_age: 30                         # 日志文件保留天数
