version: '3.8'

services:
  execmcp:
    image: ghcr.io/terateams/execmcp:latest
    container_name: execmcp-server
    restart: unless-stopped
    ports:
      - "7458:7458"
    environment:
      # 日志级别
      - EXECMCP_SERVER_LOG_LEVEL=info
      # 服务器绑定地址
      - EXECMCP_SERVER_BIND_ADDR=0.0.0.0:7458
    volumes:
      # 配置文件挂载
      - ./config.yaml:/app/config.yaml:ro
      - ./config.test.yaml:/app/config.test.yaml:ro
      # SSH 相关文件挂载 (可选)
      - ~/.ssh:/root/.ssh:ro
      # known_hosts 文件挂载 (可选)
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:ro
      # 日志目录挂载 (可选)
      - ./logs:/var/log/execmcp
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7458/mcp/sse"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - execmcp-network

networks:
  execmcp-network:
    driver: bridge

volumes:
  execmcp-logs: